#!/usr/bin/env bash

exec >>/tmp/b2_compiler_log
exec 2>>/tmp/b2_compiler_log

ROOT="$(dirname "$0")"
if [[ ${ROOT:0:1} != / ]]
then
	ROOT="$PWD/$ROOT"
fi

cd "$1"

on_exit()
{
	rm -rf "$tmp" "$tmpdir"
}
trap on_exit EXIT INT TERM

# TODO Linux only
tmpdir="$(mktemp -d)"

compile()
{
	echo "$@"
	FULL_NAME="$1"
	NAME="$(basename "$1")"
	FILE="$(basename "$2")"
	shift 2
	if ! "$@"
	then
		echo "$NAME:$FILE" >>/tmp/b2_compiler_error
		return 1
	else
		echo "$NAME:$FILE" >>/tmp/b2_compiler_ok
	fi
	case `uname` in
		Linux) tmp="$(mktemp)" ;;
		FreeBSD) tmp="$(mktemp -t /tmp)" ;;
		*) echo "Unknown system type" && exit 1;;
	esac
	cp -p "$FULL_NAME/conf.txt" "$tmp"
	case `uname` in
		Linux) sed -r -i "s|^checker=.*$|checker=check_new|" "$FULL_NAME/conf.txt" ;;
		FreeBSD) sed -r -i "" -e "s|^checker=.*$|checker=check_new|" "$FULL_NAME/conf.txt" ;;
		*) echo "Unknown system type" && exit 1;;
	esac
	touch -m -r "$tmp" "$FULL_NAME/conf.txt"
	return 0
}

TESTLIB_CPP="$ROOT/testlib/cpp/01_testlib.googlecode.com"
TESTLIB_PAS="$ROOT/testlib/pas/01_Lopatin"

if [ -d "checker" ]
then
	check_name="$(egrep '^checker=' conf.txt | sed -r 's|^checker=||')"
	cd "checker"
	rm -f check_new *.o *.ppu
	for i in *.*
	do
		case $i in
			*.cpp) compile "$1" "$i" g++ "$i" -O2 -ocheck_new -I"$TESTLIB_CPP" && break ;;
			*.c) compile "$1" "$i" gcc "$i" -O2 -ocheck_new && break ;;
			*.dpr) true ;&
			*.pas) compile "$1" "$i" fpc -O2 -Cs268435456 -Fu"$TESTLIB_PAS" -I"$TESTLIB_PAS" -FU"$tmpdir" -Mdelphi "$i" -ocheck_new && break ;;
			*.exe) ;;
			*.old) ;;
			'*.*') ;;
			*.cs) compile "$1" "$i" false ;;
			*) compile "$1" "$i" false && exit 1 ;;
		esac
	done
	rm -f *.o *.ppu
fi

